### PR TITLE
Merge latest upstream

### PR DESCRIPTION
**Pull request by nmschulte**
This brings in the latest upstream.  I think I resolved the conflicts appropriately, except for the following:

```
  @contextmanager
 -def WrapOmniSharpServer( app, filepath ):
 -  global shared_filepaths
 +def WrapOmniSharpServer( app, filepath, use_roslyn ):
 +  global shared_app_filepaths

 -  if filepath not in shared_filepaths:
 +  SetRoslynState( app, filepath, use_roslyn )
 +  if ( app not in shared_app_filepaths
 +       or filepath not in shared_app_filepaths[ app ] ):
-     StartOmniSharpServer( app, filepath )
+     StartCompleterServer( app, 'cs', filepath )
 -    shared_filepaths.append( filepath )
 -  WaitUntilCompleterServerReady( app, 'cs' )
 +    if app in shared_app_filepaths:
 +      shared_app_filepaths[ app ].append( filepath )
-   WaitUntilOmniSharpServerReady( app, filepath )
++  WaitUntilCompleterServerReady( app, 'cs', filepath )
++# WaitUntilCompleterServerReady( app, 'cs' )
    yield
```

The commented `WaitUntilCompleterServerReady( ... )` vs the not; which one...

### CODE REVIEW

**Comment by nmschulte** [comment]
Problems with stdout and stderr in my merge, too.

**Comment by nmschulte** [comment]
I pushed new code to revert the change to use the file system (stdio) over the http mechanism for stdout/err.  It also seems I've broken the AppVeyor integration in the process, @mispencer.  The Vagrant build system for ycmd seems outdated for non Mac OS platforms, and I haven't gotten it all updated to work for me (I commented out the Mac OS bits in the `Vagrantfile` and that got far, but `./run_tests.py` fails w/ python errors).

**Comment by mispencer** [comment]
This probably should be rebased instead of merged. I don't really have time to work on this at moment though.

**Comment by nmschulte** [comment]
Okay, thanks.  Can you explain why there's a difference between rebasing and merging, in this context?

**Comment by mispencer** [comment]
Rebasing this branch on master would have 10 commits, not 200 commits.

**Comment by nmschulte** [comment]
I think the conflicts would have been the same though, right?  I guess it's possible I missed a whole bunch of the changes/concerns here by merging without being fully aware of everything involved, that rebasing would have helped alleviate by taking things one commit at a time, but outside of that sort of PEBKAC, the end result is identical.  Or at least, that's the understanding I've been operating with.

I'll gladly try to push this forward in your stead; are you no longer using YouCompleteMe with .NET Core projects?

**Comment by nmschulte** [comment]
Oh!  The PR _itself_ would only ask to review 10 commits, not 200.  Gotcha!  Thanks for the tip.

**Pull request closed without merging**
